system:
  sys_path: "/home/guangyao_li/projects/avqa/music_avqa_camera_ready"
  warnings: ignore
  tensorboard_logdir: 'runs/net_avst/'
  cuda_visible_devices: '0, 1'

global:
  seed: 1
  gpu: '0, 1'

directories:
  audio_dir: '/home/guangyao_li/dataset/avqa-features/feats/vggish'
  video_res14x14_dir: '/home/guangyao_li/dataset/avqa-features/visual_14x14'
  label_train: "./data/json/avqa-train.json"
  label_val: "./data/json/avqa-val.json"
  label_test: "./data/json/avqa-test.json"
  model_save_dir: 'net_grd_avst/avst_models/'
  pretrained_file: "grounding_gen/models_grounding_gen/main_grounding_gen_best.pt"

model:
  name: 'AVQA_Fusion_Net'
  checkpoint: 'avst'
  mode: 'train'

training:
  batch_size: 64
  epochs: 80
  learning_rate: 1e-4
  log_interval: 50
  step_lr:
    step_size: 8
    gamma: 0.1